apiVersion: v1
kind: Service
metadata:
  name: mbiz-dev-ui-service
  namespace: mbiz-dev-frontend-cicd
  annotations:
spec:
  selector:
    app: mbiz-fe-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

