import { useMediaQuery } from '@mui/material';
import Box from '@mui/material/Box';
import Tab from '@mui/material/Tab';
import Tabs from '@mui/material/Tabs';
import * as React from 'react';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import FlightIcon from '../../assets/images/flight_tab.svg';
import HolidayIcon from '../../assets/images/holiday_tab.svg';
import HotelIcon from '../../assets/images/hotel_tab.svg';
import ProductBg from '../../assets/images/product_bg.svg';
import VisaIcon from '../../assets/images/visa_tab.svg';
import ErrorBoundary from '../../components/core-module/ErrorBoundry/ErrorBoundary';
import { useMenuListQuery } from '../../store/musafirHomePageApi';
import { theme } from '../../theme';
import { ROUTES } from '../../utility/constant';
import { TabPanelProps } from '../../utility/types/dashboard/Dashboard';

/**
 * CustomTabPanel component renders the content of a tab panel.
 * 
 * @param {TabPanelProps} props - The properties passed to the component.
 * @param {React.ReactNode} props.children - The content to display within the tab panel.
 * @param {number} props.value - The current value of the selected tab.
 * @param {number} props.index - The index of this tab panel.
 * @returns {JSX.Element} - A div element that acts as a tab panel.
 */
function CustomTabPanel(props: Readonly<TabPanelProps>) {
  const { children, value, index, ...other } = props;
  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && <Box sx={{ p: 0, pt: 0 }}>{children}</Box>}
    </div>
  );
}

/**
 * Generates ARIA properties for a tab element.
 * The properties are:
 * - id: The id of the tab.
 * - aria-controls: The id of the tabpanel that this tab controls.
 * @param {number} index - The index of the tab.
 * @returns {Object} - An object containing the ARIA properties.
 */
function a11yProps(index: number) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}

/**
 * BasicTabs component renders a tabbed interface with two tabs.
 * The first tab displays the flight search form, and the second tab displays a placeholder message.
 * The component uses the react-i18next library for translations.
 * The component uses the ARIA properties generated by the a11yProps function.
 * The component uses the Tabs, Tab, and Box components from the MUI library.
 * The component uses the CustomTabPanel component to render the content of each tab.
 * The component uses the sx prop to customize the appearance of the tabs and the tab bar.
 * The component uses the icon and iconPosition props to customize the appearance of the tab icons.
 * The component uses the label prop to customize the label of each tab.
 * The component uses the {t} function from the react-i18next library to translate the labels.
 * The component uses the useState hook to store the currently selected tab index in the component state.
 * The component uses the handleChange function to update the state when the user selects a new tab.
 */
const Dashboard: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const { data: menuData, error, isLoading: menuLoading, } = useMenuListQuery({});
  const [value, setValue] = useState(0);
  const imageSize = "w-6 h-6 mr-2 !mb-0";
  const [templateValue, setTemplateValue] = useState(localStorage.getItem("templateValue"));

  /**
   * Handles the change event for the tabs.
   * Updates the state to reflect the newly selected tab.
   * @param {React.SyntheticEvent} _event - The event triggered by the tab change.
   * @param {number} newValue - The index of the newly selected tab.
   */
  const handleChange = (_event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  /**
   * Handles the change event for the template tabs.
   * Updates the state to reflect the newly selected template.
   * Updates the URL query parameter to the newly selected template.
   * @param {React.SyntheticEvent} _event - The event triggered by the tab change.
   * @param {number} newValue - The index of the newly selected template.
   */

  useEffect(() => {
    const themeFromURL = new URLSearchParams(window.location.search).get("theme");
    const storedTheme = localStorage.getItem("templateValue");
    const themeValue = themeFromURL || storedTheme || "0";

    if (templateValue !== themeValue) {
      setTemplateValue(themeValue);
      localStorage.setItem("templateValue", themeValue);
      window.dispatchEvent(new Event("template-change"));
    }
  }, []);

  const handleTemplateChange = (_event: React.SyntheticEvent, newValue: number) => {
    const url = new URL(window.location.href);
    url.searchParams.set('theme', newValue.toString());
    window.history.pushState({}, '', url.toString());

    setTemplateValue(newValue.toString());
    localStorage.setItem("templateValue", newValue.toString());
    window.dispatchEvent(new Event("template-change"));
    const RedirectURL = `${ROUTES.DASHBOARD}?theme=${newValue}`
    navigate(RedirectURL)
  };


  const allTabs = [
    {
      label: t('flight_home'),
      icon: <img src={FlightIcon} alt="Flight" className={imageSize} />,
      apiKey: 'Flights',
      a11yIndex: 0,
      sx: {
        textTransform: 'none',
        minHeight: isMobile ? '53px' : '40px',
        height: isMobile ? '53px' : '40px',
        fontWeight: value === 0 ? 'bold' : 'normal',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'between',
        marginBottom: "0px !important",
        marginLeft: { md: "25px" },
        marginRight: { md: "25px" }
      },
      component: "Flight Search Coming Soon!",
    },
    {
      label: t('hotel_home'),
      icon: <img src={HotelIcon} alt="Hotel" className={imageSize} />,
      apiKey: 'Hotels',
      a11yIndex: 1,
      sx: {
        textTransform: 'none',
        minHeight: isMobile ? '53px' : '40px',
        height: isMobile ? '53px' : '40px',
        fontWeight: value === 1 ? 'bold' : 'normal',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'between',
        marginRight: { md: "25px" }
      },
      component: <>Hotel Search Coming Soon!</>,
    },
    {
      label: t('visa_home'),
      icon: <img src={VisaIcon} alt="Visa" className={imageSize} />,
      apiKey: 'Visa',
      a11yIndex: 2,
      sx: {
        textTransform: 'none',
        minHeight: isMobile ? '53px' : '40px',
        height: isMobile ? '53px' : '40px',
        fontWeight: value === 2 ? 'bold' : 'normal',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'between',
        marginRight: { md: "25px" }
      },
      component: <>Visa Search Coming Soon!</>,
    },
    {
      label: t('holidays_home'),
      icon: <img src={HolidayIcon} alt="Holiday" className={imageSize} />,
      apiKey: 'Holidays',
      a11yIndex: 3,
      sx: {
        textTransform: 'none',
        minHeight: isMobile ? '53px' : '40px',
        height: isMobile ? '53px' : '40px',
        fontWeight: value === 3 ? 'bold' : 'normal',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'between',
        marginRight: { md: "25px" }
      },
      component: <>Holidays Search Coming Soon!</>,
    },
  ];

  const pageName = "Home";
  const content = menuData?.Response?.Pages?.find(page => page?.Name?.toLowerCase() === pageName?.toLowerCase())
    ?.Sections?.find(section => section?.Category === 'Content')
    ?.Menus || []

  const availableTabs = allTabs.filter(tab =>
    content?.some(api => api?.MenuId === tab.apiKey)
  )

  return (
    <Box sx={{ width: '100%', marginTop: isMobile ? "" : "6rem", maxWidth: "1280px", marginX: "auto" }}>
      {/* Tabs Bar */}
      <Box sx={{ width: isMobile ? "70%" : "48%", marginX: "auto" }}>
        <Box sx={{
          boxShadow: 3,
          display: 'flex',
          justifyContent: 'center',
          marginTop: 6,
          position: 'sticky',
          top: 0,
          zIndex: 99,
          backgroundColor: theme?.palette?.customColors?.white[0],
          width: '100%',
          maxWidth: 'max-content',
          borderRadius: 2,
          alignItems: 'center',
          overflow: 'hidden',
          whiteSpace: 'nowrap',
        }}
        >
          <Tabs
            value={value}
            onChange={handleChange}
            aria-label="basic tabs example"
            slotProps={{
              indicator: {
                sx: { display: 'none' },
              }
            }}
            sx={{
              '& .MuiTabs-flexContainer': {
                justifyContent: 'space-between',

              },
              '& .MuiTab-root': {
                flex: 1,
                textAlign: 'center',
                flexDirection: isMobile ? 'column' : 'row',
                minWidth: 0,
                maxWidth: '100px',
                fontSize: '0.9rem',
                '@media (max-width: 600px)': {
                  fontSize: '0.75rem',
                },
              },
              ".Mui-selected": {
                color: "black !important",
              },
              ".Mui-Tab-icon": {
                color: "black !important",
              },
            }}
          >
            {availableTabs.map(tab => (
              <Tab
                key={tab.apiKey}
                label={tab.label}
                icon={tab.icon}
                {...a11yProps(tab.a11yIndex)}
                sx={tab.sx}
              />
            ))}

          </Tabs>
        </Box></Box>

      {/* MUI Tabs Section */}
      <Box sx={{
        position: 'fixed',
        top: 0,
        left: '50%',
        transform: 'translateX(-50%)',
        width: '100%',
        maxWidth: '1280px',
        height: '100%',
      }}>
        <Box sx={{
          mt: 3, mb: 2, borderBottom: 1, borderColor: 'divider', position: "absolute", right: '-5rem',
          top: '12rem',
          transform: 'rotate(90deg)',
          boxShadow: 'rgba(0, 0, 0, 0.18) 0px 2px 4px',
          borderRadius: '17px',
          backgroundColor: "#fff"
        }}

          id="template-tabs">
          <Tabs
            value={templateValue}
            onChange={handleTemplateChange}
            aria-label="template tabs"
            slotProps={{
              indicator: {
                sx: { display: 'none' },
              }
            }}
            sx={{

              '& .MuiTab-root': {
                borderRadius: "10px",

              },
              '& .MuiTab-iconWrapper.MuiTab-icon': {
                marginBottom: "0px !important",
              },
              '& .Mui-selected': {
                color: "#f1f1f1 !important",
                bgcolor: '#0087fa'
              }
            }}
          >
            <Tab
              label="Template 1"
              value={'0'}
              {...a11yProps(0)}
            />
            <Tab
              label="Template 2"
              value={'1'}
              {...a11yProps(1)}
            />
          </Tabs>
        </Box></Box>

      {/* Content */}
      <Box
        className="rounded-lg p-4 -mt-5 w-[90%] mx-auto"
        sx={{
          backgroundImage: `url(${ProductBg})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      >
        <CustomTabPanel value={value} index={0}>
          <ErrorBoundary updatedError="Failed to load flight module, Please try again later">
            <React.Suspense fallback={<div>Loading...</div>}>
              Flight Search Coming Soon!
            </React.Suspense>
          </ErrorBoundary>
        </CustomTabPanel>
        <CustomTabPanel value={value} index={1}>
          Hotel Search Coming Soon!
        </CustomTabPanel>
        <CustomTabPanel value={value} index={2}>
          Visa Search Coming Soon!
        </CustomTabPanel>
        <CustomTabPanel value={value} index={3}>
          Holidays Search Coming Soon!
        </CustomTabPanel>
      </Box>
    </Box>
  );
}
export default Dashboard
