export const CONSTANT = Object.freeze({
  EMAIL: "Email",
  SUBMIT: "Submit",
  SUCCESS: "Success",
  ERROR: "Error",
  SWW: "Something went wronge.",
  LOGIN: "Login",
  USERNAME: "Username",
  PASSWORD: "Password",
  CONFIRMPASSWORD: "Confirm Password",
  ONEWAY: "ONEWAY",
  ROUNDTRIP: "ROUNDTRIP",
  MULTICITY: "MULTICITY"
});
export const ROUTES = Object.freeze({
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  ROLES: "/roles",
  USER: "/users",
  MARKETS: "/markets",
  ACL: "/acl",
  ADDORG: "/addorg",
  ORGANIZATIONS: "/organizations",
  EMAILTEMPLATE: "/email-template",
  EMAILTEMPLATEEDITOR: "/email-template-editor",
  EDITUSER: "/user/update",
  ADDUSER: "/user/create",
  SRP: "/flight-search",
  CHECKOUT: '/checkout',
  CHECKOUTRULES: '/checkout-rules',
  CHECKOUTTERMS: '/CheckoutTerms',
  CHECKOUTPRIVACY: '/CheckOutPrivacy',
  PAYMENT: '/payment',
  PAYMENTFAIL: "payment/failed",
  BookDetails: '/bookdetail',
  CALLBACK: '/call-back',
  SAMLCALLBACK:'/saml-callback',
  TRIPS: '/trips',
  ADDNEWTRAVELER: '/addnewtraveler',
  NEWTRIP: '/newtrip',
  APPROVALWORKFLOW: '/approval-workflow',
  TRAVEL_POLICY: '/travel-policy',
  ORGANISATIONS: '/organisations',
  TAGS: '/tags',
  MARKET_PLACE: '/market-place',
  WHITELABEL_SETTINGS: '/whitelabel-settings',
  FINANCE: '/finance',
  REPORTS: '/reports',
  FLIGHTANCILLARIES: '/flightAncillaries',
  POLICY: '/policy',
  SUPPORT: '/support',
  QUOTATION: '/quotation',
  PRICING_POLICY: '/pricing-policy',
  VOUCHER: '/voucher',
  OFFER: '/offer',
  BUDGET:'/budget',
  NOTFOUND: '/not-found',
  NOTAUTHORIZED: '/not-authorized',
});
export const ERROR_MESSAGE = Object.freeze({
  INVALID_EMAIL: "Invalid email",
  INVALID_PASSWORD: "Password cannot be empty",
  MISMATCHED_PASSWORD: "Passwords did not match",
});
